config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :users
  resources :vegetables
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :vegetables, dependent: :destroy
end

app/models/vegetable.rb
class Vegetable < ApplicationRecord
  belongs_to :user
  attachment :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to users_path, alert: "アクセスできません。"
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "更新しました。"
      redirect_to user_path(@user)
    end
  end

  def destroy
    @vegetable = Vegetable.find(params[:id])
    @vegetable.destroy
    redirect_to vegetables_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :profile, :profile_image)
  end
end

app/controllers/vegetables_controller.rb
class VegetablesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @vegetables = Vegetable.all
  end

  def show
    @vegetable = Vegetable.find(params[:id])
  end

  def new
    @vegetable = Vegetable.new
  end

  def create
    @vegetable = Vegetable.new(vegetable_params)
    @vegetable.user_id = current_user.id
    @vegetable.save
    redirect_to vegetable_path(@vegetable)
  end

  def edit
    @vegetable = Vegetable.find(params[:id])
    if @vegetable.user != current_user
      redirect_to vegetables_path, alert: "アクセスできません。"
    end
  end

  def update
    @vegetable = Vegetable.find(params[:id])
    if @vegetable.update(vegetable_params)
      redirect_to vegetable_path(@vegetable), notice: "更新しました。"
    else
      render :edit
    end
  end

  private
    def vegetable_params
      params.require(:vegetable).permit(:title, :body, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vegetables_helper.rb
module VegetablesHelper
end

app/views/home/index.html.erb
<section class="section">
  <article class="media">
    <div class="media-content">
      <div class="content has-text-centered">
        <p><strong class="is-size-1" style="font-family: cursive;">VegeShare</strong></p>
        <p class="is-size-3">大切に育てた野菜をあなたのもとへ</p>
      </div>
      <div class="columns is-centered">
        <div class="column">
          <figure>
            <div class="main-image"></div>
          </figure>
        </div>
      </div>
    </div>
  </article>
  <br>
  <div class="columns is-centered">
    <div class="column is-5"><br>
      <%= link_to "ログイン", new_user_session_path, class: "button is-light is-fullwidth" %><br>
      <%= link_to "新規登録", new_user_registration_path, class: "button is-light is-fullwidth" %>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VegeShare</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="notice"><%= alert %></p>
      </div>
    <% end %>

    <nav class="navbar is-success">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-4" style="font-family: cursive; color :white;">VegeShare</h1>
        <% end %>
        <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

      <% if user_signed_in? %>
        <div id="navbarExampleTransparentExample" class="navbar-menu">
          <div class="navbar-item">
            <%= link_to "新規登録", new_vegetable_path, class: "navber-item button is-light" %>
          </div>
          <div class="navbar-item">
            <%= link_to "登録野菜一覧", vegetables_path, class: "navber-item button is-light" %>
          </div>

          <div class="navbar-end">
            <div class="navbar-item">
              <div class="field is-grouped">
                <p class="control">
                  <%= link_to "ユーザー一覧", users_path, class: "button is-light" %>
                </p>
                <p class="control">
                  <%= link_to "マイページ", user_path(current_user), class: "button is-light"%>
                </p>
                <p class="control">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "button is-light" %>
                </p>
              </div>
            </div>
          </div>
        </div>
      <% else %>
        <div id="navbarExampleTransparentExample" class="navbar-menu">
          <div class="navbar-item">
            <%= link_to "登録野菜一覧", vegetables_path, class: "navber-item button is-light" %>
          </div>
          <div class="navbar-item">
            <%= link_to "ユーザー一覧", users_path, class: "button is-light" %>
          </div>
          <div class="navbar-end">
            <div class="navbar-item">
              <div class="field is-grouped">
                <p class="control">
                  <%= link_to "ログイン", new_user_session_path, class: "button is-success is-light" %>
                </p>
                <p class="control">
                  <%= link_to "新規登録", new_user_registration_path, class: "button is-success is-light" %>
                </p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </nav>
    <%= yield %>
    <footer>
      <p class="footer-text">&copy; All rights reserved by Matsu</p>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<section class="hero is-light">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ユーザー編集
      </h1>
    </div>
  </div>
</section>


<% if @user.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @user do |f| %>
          <div class="field">
            <%= f.label :username, "ユーザー名", class: "label" %>
            <%= f.text_field :username, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :email, "メールアドレス", class: "label" %>
            <%= f.email_field :email, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :profile, "プロフィール", class: "label" %>
            <%= f.text_area :profile, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :profile_image, "プロフィール画像", class: "label" %>
            <%= f.attachment_field :profile_image, class: "input" %>
          </div>

          <%= f.submit "更新", class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>

app/views/users/index.html.erb
<section class="hero is-light">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ユーザー一覧
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @users.each do |user| %>
        <div class="column is-3">
          <div class="card">
            <div class="card-content">
              <div class="card-image">
                <figure class="image">
                  <%= link_to user_path(user) do %>
                    <%= attachment_image_tag user, :profile_image, :fill, 300, 300, fallback: "no-image.png" %>
                  <% end %>
                </figure>
              </div>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <div class="title"><%=link_to user.username, user_path(user) %></div>
                </div>
              </div>
              <div class="content">
                投稿数:<%= user.vegetables.count %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="hero is-light">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        マイページ
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <div class="columns is-centered">
          <div class="column is-4">
            <figure class="image is-128x300"  style="margin-left: auto; margin-right: auto;">
              <%= attachment_image_tag @user, :profile_image, :fill, 300, 300, fallback: "no-image.png", class: "profile_image is-rounded" %>
            </figure>
          </div>
          <div class="column is-8">
            <table class="table is-fullwidth">
              <tr>
                <td class="is-size-4">
                  <strong><%= @user.username %></strong>
                </td>
                <% if @user.id == current_user.id %>
                <td class="is-size-4">
                  <%= @user.email %>
                </td>
                <td>
                  <%= link_to "編集", edit_user_path(@user), class: "button is-primary" %>
                </td>
                <% end %>
              </tr>
            </table>
            <table class="table is-fullwidth">
              <tr>
                <td>
                  <%= @user.profile %>
                </td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @user.vegetables.each do |vegetable| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
              <%= link_to vegetable_path(vegetable) do %>
                <%= attachment_image_tag vegetable, :image%>
              <% end %>
            </figure>
          </div>
          <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <%= link_to vegetable_path(vegetable), class: "panel-block" do %>
                    <span class="panel-icon">
                      <i class="fas fa-carrot" aria-hidden="true"></i>
                    </span>
                    詳しく見る
                  <% end %>
                  <% if @user.id == current_user.id %>
                    <%= link_to edit_vegetable_path(vegetable), class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-edit"></i>
                      </span>
                      編集する
                    <% end %>
                    <%= link_to vegetable_path(vegetable), method: :delete, data: {confirm: "削除しますか？"}, class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-trash"></i>
                      </span>
                      削除する
                    <% end %>
                  <% end %>
                </div>
              </div>
              <div class="content">
                <time><%= vegetable.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/vegetables/edit.html.erb
<section class="hero is- light">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        編集
      </h1>
    </div>
  </div>
</section>

<% if @vegetable.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@vegetable.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @vegetable.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @vegetable do |f| %>
          <div class="field">
            <%= f.label :title, "品名名", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "内容", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.attachment_field :image, class: "input" %>
          </div>

          <%= f.submit '投稿', class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/vegetables/index.html.erb
<section class="hero is-light">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        野菜投稿一覧
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @vegetables.each do |vegetable| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to vegetable_path(vegetable) do %>
                  <%= attachment_image_tag vegetable, :image %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-left">
                  <figure class="image is-48x48">
                    <%= attachment_image_tag vegetable.user, :profile_image, :fill, 300, 300, fallback: "no-image.png", class: "profile_image" %>
                  </figure>
                </div>
                <div class="media-content">
                  <div class="title"><%=link_to vegetable.user.username, user_path(vegetable.user) %></div>
                </div>
              </div>

              <div class="content">
                <time><%= vegetable.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/vegetables/new.html.erb
<section class="hero is-light ">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        野菜新規登録
      </h1>
    </div>
  </div>
</section>


<% if @vegetable.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@vegetable.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @vegetable.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_with model: @vegetable do |f| %>
          <div class="field">
            <%= f.label :title, "品名", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "内容", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.attachment_field :image, class: "input" %>
          </div>

          <%= f.submit '投稿', class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/vegetables/show.html.erb
<section class="hero is-light">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        詳細
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-7">
        <div class="card">
          <div class="card-image">
            <figure class="image is-4by3">
              <%= attachment_image_tag @vegetable, :image %>
            </figure>
          </div>
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                <p class="title is-4"><%= @vegetable.title %></p>
              </div>
            </div>
            <div class="content">
              <table class="table is-narrow">
                <tr>
                  <th>レシピ</th>
                </tr>
                <tr>
                  <td><%= simple_format @vegetable.body %></td>
                </tr>
              </table>
              <% if @vegetable.user.id == current_user.id %>
                <%= link_to "編集画面へ", edit_vegetable_path(@vegetable), class: "button is-success" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <div class="column is-4">
        <article class="panel is-link">
          <p class="panel-heading">
            By <%= @vegetable.user.username %>
          </p>
          <div class="panel-block">
            <p class="control">
              <%= @vegetable.user.profile %>
            </p>
          </div>
          <%= link_to user_path(@vegetable.user), class: "panel-block" do %>
            <span class="panel-icon">
              <i class="fas fa-user" aria-hidden="true"></i>
            </span>
            <%= @vegetable.user.username %> さんのページへ
          <% end %>
        </article>
      </div>
    </div>
  </div>
</section>